name: GitHub Actions Test

on:
  push:
    branches:
      - master
 env:
   APP_NAME: github_Actions_Mocha
description: "Test Code"
jobs:

  testCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: Install mocha
        run:  npm install -g mocha
      - name: 'install should'
        run:  npm install mocha-should --save-dev
      - name: Install dependencies
        run:  npm install
      - name: "Run Test"
        run:  mocha test/test.js
