name: GitHub Actions Test
on:
  push:
    branches:
      - master
jobs:
  testCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: Install mocha
        run:  npm install -g mocha
      - name: 'install should'
        run:  npm install mocha-should --save-dev
      - name: Install dependencies
        run:  npm install
      - name: "Run calculationTest"
        run:  mocha test/test.js
      - name: "Run other tests"
        run:  mocha test/otherTest.js
      - name: "run existing tests"
        run: npm test
      - name: my-step
        run: echo "Hello World!"
