name: GitHub Actions Test

on:
  push:
    branches:
      - master
jobs:

  testCode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: Install mocha
        run: npm install -g mocha
      - name: Install dependencies
        run: npm install
      - name: "Run Test"
        run: mocha test/test.js
